### PR TITLE
feat(main): add ability to have elb and instances in different subnets

### PR DESCRIPTION
**Pull request by jkurz**
- we need to be able to put elbs in public subnets and the instances in private subnets

### CODE REVIEW

**Comment by smithatlanta** [comment]
LGTM.  I'm going to pull and add the other items we discussed.

**Comment by jkurz** [comment]
can we just merge this? and then do another PR for those things?

**Comment by jkurz** [comment]
I like to keep PRs small and to the point. If and whenever possible.

**Comment by smithatlanta** [comment]
Sure. Go ahead and merge it.

**Pull request merged**
